org: orgDemo
app: appDemo
stage: dev

component: django
name: djangoDemo

inputs:
  region: ap-guangzhou
  djangoProjectName: mydjangocomponent
  src: ./src
  functionConf:
    timeout: 10
    memorySize: 256
    environment:
      variables:
        TEST: vale
  apigatewayConf:
    protocols:
      - https
    environment: release
